#workflow name
name: Docker-Git Action Automation

# Run workflow on every push to main branch.
on:
  push:
    branches: [main]
# workflows jobs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
# Automate function 1 : Docker build command  
    - name: docker build python
      run: |
        docker build -t bonny2512/hello-world-action
# Automate function 2 : Docker push command    
    - name: docker push
      run: |
        docker push bonny2512/hello-world-action:latest
